# Generated by Django 3.0.6 on 2020-05-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vicer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=50)),
                ('Last_name', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(default='', max_length=100, unique=True)),
                ('Department', models.CharField(choices=[('FLER', 'FLER'), ('IT', 'IT'), ('HR', 'HR'), ('COMM', 'COMM')], default='FLER', max_length=4)),
                ('Year_joined_VIC', models.IntegerField(default=0)),
            ],
        ),
    ]
